Update Ansible Deployment.yml

diff --git a/.github/workflows/Ansible Deployment.yml b/.github/workflows/Ansible Deployment.yml
--- a/.github/workflows/Ansible Deployment.yml
+++ b/.github/workflows/Ansible Deployment.yml
@@ -23,15 +23,15 @@ jobs:
           echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
-          if [ -z "${{ secrets.EC2_HOST }}" ]; THEN
-             echo "EC2_HOST is empty"
-             exit 1
-          fi
-          
-          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
-            echo "ss-keyscan failed"
+          if [ -z "${{ secrets.EC2_HOST }}" ]; then
+            echo "EC2_HOST is empty"
             exit 1
-          }            
+          fi
+
+          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || {
+            echo "ssh-keyscan failed"
+            exit 1
+          }
 
       - name: Create Ansible inventory
         run: |
@@ -42,4 +42,4 @@ jobs:
         run: |
           ansible-playbook ansible/Deploy.yml -i inventory \
             -e "docker_user=${{ secrets.DOCKER_USER }}" \
-            -e "docker_password=${{ secrets.DOCKER_PASSWORD }}"
+            -e "docker_password=${{ secrets.DOCKER_PASSWORD }}"
