Update Ansible Deployment.yml

diff --git a/.github/workflows/Ansible Deployment.yml b/.github/workflows/Ansible Deployment.yml
--- a/.github/workflows/Ansible Deployment.yml
+++ b/.github/workflows/Ansible Deployment.yml
@@ -22,7 +22,16 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
+
+          if [ -z "${{ secrets.EC2_HOST }}" ]; THEN
+             echo "EC2_HOST is empty"
+             exit 1
+            fi
+          
           ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+            echo "ss-keyscan failed"
+            exit 1
+          }            
 
       - name: Create Ansible inventory
         run: |
